let musicDB = [
    {
        id: 0,
        name: "NgaGiChoeLu",
        author: "somWangchen",
        img: "b1.jpg",
        timesPlayed: 0,
        type: "rigsar",
        song: "s0.mp3",
    },
    {
        id: 1,
        name: "Dendray Phar",
        author: "Dorji",
        img: "b2.jpg",
        timesPlayed: 0,
        type:"boedra",
        song: "s1.mp3",
    },
    {
        id: 2,
        name: "Bum Jarim",
        author: "Augay",
        img: "b6.jpg",
        type: "rigsar",
        timesPlayed: 0,
        song: "s2.mp3",
    },
    {
        id: 3,
        name: "Gaa",
        author: "Kenny",
        img: "b5.jpg",
        timesPlayed: 0,
        type: "rigsar",
        song: "s3.mp3",
    },
    {
        id: 4,
        name: "Boedra mix",
        author: "Pema group",
        img: "b4.jpg",
        timesPlayed: 0,
        type: "boedra",
        song: "s4.mp3",
    },
    {
        id: 5,
        name: "Sexy Body",
        author: "Kado",
        img: "b7.jpg",
        timesPlayed: 0,
        type: "rigsar",
        song: "s5.mp3",
    },
    {
        id: 6,
        name: "Amo chi",
        author: "Tshomo",
        img: "b3.jpg",
        timesPlayed: 0,
        type:"zhungdra",
        song: "s6.mp3",
    },
    {
        id: 7,
        name: "GangLing",
        author: "Aup Dawpay",
        img: "b8.jpg",
        timesPlayed: 0,
        type:"boedra",
        song: "s7.mp3",
    },
    {
        id: 8,
        name: "SenNa",
        author: "Nima Wangyel",
        img: "b9.jpg",
        timesPlayed: 0,
        type: "rigsar",
        song: "s8.mp3",
    }
];

export default musicDB;